# in _config.yml
title:
author: Bruce Emerson
logo: imagesBarca22/Barca22Logo.png

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# "off" reuses cached output unless ipynb has changed.
execute:
  execute_notebooks: "force"
  
html:
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
    </p>
